version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app:latest
    container_name: react-app-container
    ports:
      - "81:80" # React served via Nginx
    restart: always
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
